# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 18:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinstance',
            old_name='impriint',
            new_name='imprint',
        ),
    ]
